# Generated by Django 5.1.6 on 2025-10-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('price', models.CharField(max_length=50)),
                ('best_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='membershipcard',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('capital', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('best_time', models.CharField(max_length=100)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='users.region')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('best_time', models.CharField(max_length=100)),
                ('attractions', models.JSONField(blank=True, default=list)),
                ('hotels', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='users.country')),
            ],
            options={
                'unique_together': {('country', 'name')},
            },
        ),
    ]
