# Generated by Django 5.1.6 on 2025-10-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_region_alter_membershipcard_price_alter_user_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonushistory',
            name='type',
            field=models.CharField(choices=[('referral', 'Referral Bonus'), ('cashback', 'Cashback Bonus')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='monthly_limit',
            field=models.PositiveIntegerField(blank=True, help_text='None = без лимита', null=True),
        ),
    ]
