# Generated by Django 5.1.6 on 2025-10-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bonushistory_type_membershipcard_bonus_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonushistory',
            options={'verbose_name': 'История бонусов', 'verbose_name_plural': 'История бонусов'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='membershipcard',
            options={'verbose_name': 'Карта членства', 'verbose_name_plural': 'Карты членства'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='usermembership',
            options={'verbose_name': 'Карта пользователя', 'verbose_name_plural': 'Карты пользователей'},
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Процент стандартной скидки'),
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='discount_tours',
            field=models.PositiveIntegerField(default=0, help_text='Количество туров со стандартной скидкой'),
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='extra_discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Процент доп. скидки'),
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='extra_discount_tours',
            field=models.PositiveIntegerField(default=0, help_text='Доп. количество туров со скидкой'),
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='transfers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='users.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='type',
            field=models.CharField(choices=[('referral', 'Реферальный бонус'), ('cashback', 'Кешбэк')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
