# Generated by Django 5.1.6 on 2025-10-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_bonushistory_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='price',
            field=models.IntegerField(default=0, help_text='Базовая цена тура в этом городе'),
        ),
    ]
