# Generated by Django 5.1.6 on 2025-10-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_city_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='hotels',
        ),
        migrations.RemoveField(
            model_name='region',
            name='price',
        ),
        migrations.RemoveField(
            model_name='region',
            name='rating',
        ),
    ]
