# Generated by Django 5.1.6 on 2025-10-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_city_hotels_remove_region_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonushistory',
            name='type',
        ),
        migrations.RemoveField(
            model_name='membershipcard',
            name='max_tours',
        ),
    ]
